Creating Item Card component.
Different-OpenSource/DigitalMenu pull request #7
Opened 2023-05-30 21:50 UTC by JoaoGranzinoli

Changes:

- Creating Components folder
- Creating ItemCard folder
- Creating index and CSS files for ItemCard

![itemcard](https://github.com/Different-OpenSource/DigitalMenu/assets/54122328/244ef764-66ab-4fdf-bcdc-126a905624b4)

2023-06-04 19:39 UTC, lnardon requested changes

2023-06-04 19:39 UTC, lnardon commented on package.json
> +    "@types/react-router-dom": "^5.3.3",
Falta remover essas bibliotecas de router. Procurar como remover ela usando algo como `npm remove` ou algo parecido.

2023-06-04 19:39 UTC, lnardon commented on src/app/components/ItemCard/index.tsx
> +import './ItemCard.css';
Trocar aqui para utilizar modulos do css. O arquivo de estilo eh `styles.module.css`.

2023-06-04 19:39 UTC, lnardon commented on src/app/components/ItemCard/index.tsx
> +    <div className="item-card" onClick={handle_click}>
Trocar todas as classes para usar modulos de css. `className={styles.container}`. Procure como foi feito nos outros componentes,

2023-06-15 00:49 UTC, diegozklein commented on package.json
> +    "@types/react-router-dom": "^5.3.3",
Refatorado

2023-06-15 00:49 UTC, diegozklein commented on src/app/components/ItemCard/index.tsx
> +import './ItemCard.css';
Refatorado

2023-06-15 00:49 UTC, diegozklein commented on src/app/components/ItemCard/index.tsx
> +    <div className="item-card" onClick={handle_click}>
Refatorado

2023-06-20 04:31 UTC, lnardon approved these changes

2023-06-20 04:31 UTC, merged