Feat/restaurant banner
Different-OpenSource/DigitalMenu pull request #9
Opened 2023-06-02 18:31 UTC by HamesterFelipe

Create basic restaurant banner, and icon button(going to improve later)

2023-06-03 21:08 UTC, lnardon requested changes

2023-06-03 21:08 UTC, lnardon commented on public/restaurantBanner.jpg
Remover arquivo

2023-06-03 21:08 UTC, lnardon commented on public/restaurantBanner2.jpg
Remover arquivo

2023-06-03 21:08 UTC, lnardon commented on src/components/banner/banner.tsx
> +import styles from './banner.module.css'
Trocar para nome padronizado  `styles.module.css`

2023-06-03 21:08 UTC, lnardon commented on src/components/banner/banner.tsx
> +    useEffect(() => {
Remover codigo sem uso

2023-06-03 21:08 UTC, lnardon commented on src/components/iconButton/iconButton.tsx
> +import React from 'react';
N precisa importar React aqui

2023-06-03 21:08 UTC, lnardon commented on src/components/iconButton/iconButton.tsx
> +import styles from './iconButton.module.css';
Trocar para o nome padrao

2023-06-03 21:08 UTC, lnardon commented on public/icons/left-arrow24px.svg
Remover o `24px` do nome

2023-06-03 21:08 UTC, lnardon commented on public/icons/right-arrow24px.svg
Remover o `24px` do nome

2023-06-14 00:24 UTC, lnardon requested changes

2023-06-14 00:24 UTC, lnardon commented on src/components/banner/banner.tsx
> +import Image from 'next/image'
- Trocar nome do folder para `Banner`
- Trocar nome do arquivo para index.tsx

2023-06-14 00:24 UTC, lnardon commented on src/components/iconButton/iconButton.tsx
> +import styles from './styles.module.css';
- Trocar nome do folder para `IconButton`
- Trocar nome do arquivo para index.tsx

2023-06-15 00:29 UTC, diegozklein commented on src/components/iconButton/iconButton.tsx
> +import styles from './styles.module.css';
Feito

2023-06-15 00:29 UTC, diegozklein commented on src/components/banner/banner.tsx
> +import Image from 'next/image'
Feito

2023-06-22 01:38 UTC, lnardon submitted a review, later dismissed

2023-06-22 01:40 UTC, lnardon commented
Favor arrumar o PR, o build esta falhando. @HamesterFelipe

2023-06-22 01:49 UTC, lnardon approved these changes

2023-06-22 01:49 UTC, merged